spring:
  datasource:
    url: jdbc:mysql://${thefronts.datasource.ip}:3306/file_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${thefronts.datasource.username}
    password: ${thefronts.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.thefronts.file.model
  global-config:
    db-config:
      id-type: INPUT

thefronts:
  file-server:
    type: s3
    #fdfs:
    #  web-url: ${thefronts.fdfs.web-url}
    s3:
      access-key: ${thefronts.s3.access-key}
      accessKeySecret: ${thefronts.s3.accessKeySecret}
      endpoint: ${thefronts.s3.endpoint}
      bucketName: ${thefronts.s3.bucketName}
  swagger:
    enabled: true
    title: 文件中心
    description: 文件中心接口文档
    version: 1.0
    base-package: cn.thefronts.file.controller
  #多租户配置
  tenant:
    enable: true

#fastDFS配置
#fdfs:
#  soTimeout: 1500
#  connectTimeout: 600
#  trackerList: ${thefronts.fdfs.trackerList}